backend:
  name: github
  repo: desmon91/desmond-s-website
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: "src/pages/blog"
    create: true
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title, widget: string }
      - { name: "thumbnail", label: "Thumbnail", widget: image }
      - { name: body, label: Body, widget: markdown }
      - { label: "Tags", name: "tags", widget: "list" }
